def setup_mate_in_two_board(self):
    self.add_material("WQb8")
    self.add_material("Wb3")
    self.add_material("Wf2")
    self.add_material("Wg3")
    self.add_material("Wh6")
    self.add_material("WKh2")
    self.add_material("WBg2")
    self.add_material("BQa2")
    self.add_material("Ba7")
    self.add_material("BBe6")
    self.add_material("BKf6")
    self.add_material("Bf5")
    self.add_material("Bf7")
    self.add_material("Bg6")
    self.add_material("Bh7")

def setup_vision_ray_test_board(self):
    self.add_material("Ba7")
    self.add_material("Bb4")
    self.add_material("Bc3")
    self.add_material("Bd2")
    self.add_material("Bf2")
    self.add_material("Bh4")
    self.add_material("Bd6")
    self.add_material("Bg7")
    self.add_material("Wd1")
    self.add_material("Wf6")
    self.add_material("Wd8")
    self.add_material("Wg4")
    self.add_material("Bc6")
    self.add_material("Bf5")
    self.add_material("Wc2")
    self.add_material("We2")
    self.add_material("Wf3")
